### ISSUE TITLE
Version 0.2.0 now conflicts w/Thaumic Tinkerer

### ISSUE THREAD

**Issue by mahilo3550** [simibubi/TheMightyArchitect#1]
Didn't have this problem with version 0.1.3. Here's link of essential error code from log https://jpst.it/1ETJ8

**Comment by mahilo3550** [comment]
Remove Thaumic Tinkerer and had a compatibility issue w/ Thermal Dynamics. https://jpst.it/1ETLc

**Comment by simibubi** [comment]
Thanks for reporting, this will be fixed in the next version:
https://github.com/simibubi/TheMightyArchitect/commit/7283d4ee2e1064bfa64637e83de8a5c2c2745418
