### ISSUE TITLE
Crash w/ Furniture Mod

### ISSUE THREAD

**Issue by WenXin20** [simibubi/TheMightyArchitect#2]
Minecraft v1.12.2
Forge v14.23.5.2821
Mighty Architect v0.2.0
[Mr. Crayfish's Furniture](https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod) v6.2.0

I got this while trying to load up the game. 
Here's the [crash log](https://paste.dimdev.org/udozanevod.mccrash).

**Comment by simibubi** [comment]
Blimey, this compat issue is pretty severe.
It's practically the exact same reason why the mods in the other issues crash. This should be fixed and shipped with 0.2.1 very soon.
Thank you for sharing!

**Comment by WenXin20** [comment]
Thanks!
