### ISSUE TITLE
[Feature Request] Please add a survival friendly mode.

### ISSUE THREAD

**Issue by JadianRadiator** [simibubi/TheMightyArchitect#4]
When I saw this mod, I though that it would make making train bridges easy for both staff and players.
Unfortunately it "cheats" the blocks in. Or at least it does in single player survival.
So I went to look through the config files to see if I could correct that...
only to find that there are no config files for this mod.
Edit: The train mod being Immersive Railroading.

**Comment by simibubi** [comment]
Hi JadianRadiator, thanks for your request!
And it's true, TMA does not come with a 'legit' schematic printer. It is designed to be a client-side mod that helps you **generate** schematic files. Though with the help of other mods you can achieve what you're after, have a look [here](https://github.com/simibubi/TheMightyArchitect/wiki/User-Guide#exporting-your-build). 

My plan for 1.14 is to release a second mod to allow printing schematics more easily and survival friendly.
