### ISSUE TITLE
[1.14.4] when you go in to designer mode when in pitch black you can't see anything.

### ISSUE THREAD

**Issue by ProsperCraft** [simibubi/TheMightyArchitect#5]
![2019-08-01_16 57 23](https://user-images.githubusercontent.com/4427684/62332591-806c3e80-b47d-11e9-97a3-21c65771f13d.png)

**Comment by simibubi** [comment]
Hi, thanks for your Issue.

However, not being able to see in the dark is a mechanic of the game, don't you think?
I agree that the celshading might take the last bit of contrast you could've seen otherwise. 
If you have no way to light up your building site, you can press [**F4**] to disable the shader.

**Comment by ProsperCraft** [comment]
I guess I should have stated that the main issue is not being able to get out of build mode because you can't see the menu.

**Comment by simibubi** [comment]
The Menu shouldn't be affected by the shader or brightness, it renders similarly to your hotbar. 
Is it just not visible at all?

**Comment by ProsperCraft** [comment]
I thought I had the menu up and could not see it, I resolved it by relogging to the server, I guess this goes to another issue I have been meaning to file, once in that mode, players are stuck and can't figure out how to get out of it, and it seems like there is more than one way, one if you have entered in to a type of design, and another holding down keys, we keep having players trapped and asking how to get out, perhaps there could be a persistent instruction on that screen explaining how to get out?  I was considering unmapping the key so only players that know what they are doing would go in there, no go in by tapping a key accidentally and getting trapped and not be able to get out without reading the wiki online.

**Comment by simibubi** [comment]
The fastest way to exit any stage of the design process is by hitting [**G**] -> [**U**],
_G being the key for opening the menu._

If you have this tool in a mod collection, I highly suggest re- or unbinding the key to prevent the menu from popping up on accident.
I will look into adding more panic-exits for those who didn't enter it on purpose.

**Comment by simibubi** [comment]
As of TMA 0.4.4, 
**ESC** will get you out of the composer aswell.
Are there any more concerns related to what this issue was initially referring to?
