### ISSUE TITLE
it doesnt work, when i press the 'g' key the menu doesnt open up

### ISSUE THREAD

**Issue by ZephyrFaiz** [simibubi/TheMightyArchitect#6]

**Comment by simibubi** [comment]
Hi, and thanks for reporting.
Check the Controls section of your in-game options and look for "Start Composing". 
Is it bound to G? 
Is it colliding with other Keybinds?

**Comment by ZephyrFaiz** [comment]
nope, i even tried deleting my other mods but it wouldnt work still

**Comment by simibubi** [comment]
What version of **The Mighty Architect**, and what version of **Forge** have you got installed?
If you get the chance to, drop your `lastest.log` on a [Gist](https://gist.github.com/), a [Pastebin](https://pastebin.com/) or other platforms, it'll become much easier to find the issue you're experiencing. You can find it in `<packfolder>/logs/`.

**Comment by ZephyrFaiz** [comment]
thanks ill go check em out and see if the problems fixed

**Comment by MonTheR14** [comment]
hello there ... I have the same issue. G won't work and no Start Composing in control section.
MC ver. 1.14.4
my forge ver. 28.0.45
The Mighty Arch... ver. 0.4.4
Latest Log in here: https://gist.github.com/MonTheR14/a12865ebc69898480f48776510032102

**Comment by simibubi** [comment]
Thanks for your input. 
Fix this issue by updating to **0.4.5**, the latest forge update rendered previous TMA versions unusable.
