### ISSUE TITLE
[1.14.4] Incompatability with Forge Version

### ISSUE THREAD

**Issue by Morpheus1101** [simibubi/TheMightyArchitect#8]
Im running Forge 28.0.9 however the mod dosent like it and is requiring 28.0.45 or higher, which obviously im using.

**Comment by simibubi** [comment]
Hi Morpheus,
in Forge versioning, later versions get higher numbers. Therefore 28.0.9 (released July 20th) is far more outdated than 28.0.45 or the current latest version 28.0.83.
I'm guessing the Twitch Launcher got them a little scrambled with its sorting order.
